remote_theme: github-profile-achievements/jekyll-theme

title: Список значков и достижений студентов IT-INCUBATOR
description: Список значков и достижений студентов IT-INCUBATOR
lang: ru
logo_url: https://avatars.githubusercontent.com/u/117988194?s=200&v=4
